# Generated by Django 3.2 on 2022-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('engridients', models.TextField(max_length=700)),
                ('price', models.FloatField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
