# Generated by Django 4.1.3 on 2022-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_choco_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('pages', models.IntegerField(default=70)),
                ('price', models.FloatField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('engridients', models.TextField(max_length=700)),
                ('price', models.FloatField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('height', models.IntegerField(default=10)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.TextField(max_length=20)),
                ('price', models.FloatField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('users', models.IntegerField(default=50000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uniform', models.CharField(max_length=50)),
                ('selery', models.IntegerField(default=1000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
